steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'functions',
        'deploy',
        'HttpHandler',
        '--trigger-http',
        '--runtime',
        'go113',
      ]
